export const MESSAGE_KEYS = {
  UNKNOWN_SUCCESS: "message:unknownSuccess",
  USER_CREATED: "message:userCreated",
  USER_DELETED: "message:userDeleted",
  PASSWORD_UPDATED: "message:passwordUpdated",
  PASSWORD_RESET_EMAIL_SENT: "message:passwordResetEmailSent",
  LOGGED_IN_SUCCESSFULLY: "message:loggedInSuccessfully",
  LOGGED_OUT_SUCCESSFULLY: "message:loggedOutSuccessfully",
  USER_PROFILE_UPDATED: "message:userProfileUpdated",
  ADDED_TO_FAVORITES: "message:addedToFavorites",
  ADDED_TO_FEATURED: "message:addedToFeatured",
  ADDED_TO_GLOSSARY: "message:addedToGlossary",
  CONNECTED_WITH_GLOSSARY: "message:connectedWithGlossary",
  READING_PROGRESS_SAVED: "message:readingProgressSaved",
  COPIED_TO_CLIPBOARD: "message:copiedToClipboard",
  SEARCH_KEYWORD_TOO_SHORT: "message:searchKeywordTooShort",
} as const;