import { BookKey } from "../@types";

export const BookKeys = {
  "GEN": { "id": 1, "title": "genesis", "writer": "moses", "len": 50 },
  "EXO": { "id": 2, "title": "exodus", "writer": "moses", "len": 40 },
  "LEV": { "id": 3, "title": "leviticus", "writer": "moses", "len": 27 },
  "NUM": { "id": 4, "title": "numbers", "writer": "moses", "len": 36 },
  "DEU": { "id": 5, "title": "deuteronomy", "writer": "moses", "len": 34 },
  "JOS": { "id": 6, "title": "joshua", "writer": "joshua", "len": 24 },
  "JDG": { "id": 7, "title": "judges", "writer": "samuel", "len": 21 },
  "RUT": { "id": 8, "title": "ruth", "writer": "samuel", "len": 4 },
  "1SA": { "id": 9, "title": "samuel1", "writer": "samuel", "len": 31 },
  "2SA": { "id": 10, "title": "samuel2", "writer": "samuel", "len": 24 },
  "1KI": { "id": 11, "title": "kings1", "writer": "jeremiah", "len": 22 },
  "2KI": { "id": 12, "title": "kings2", "writer": "jeremiah", "len": 25 },
  "1CH": { "id": 13, "title": "chronicles1", "writer": "ezra", "len": 29 },
  "2CH": { "id": 14, "title": "chronicles2", "writer": "ezra", "len": 36 },
  "EZR": { "id": 15, "title": "ezra", "writer": "ezra", "len": 10 },
  "NEH": { "id": 16, "title": "nehemiah", "writer": "nehemiah", "len": 13 },
  "EST": { "id": 17, "title": "esther", "writer": "mordecai", "len": 10 },
  "JOB": { "id": 18, "title": "job", "writer": "moses", "len": 42 },
  "PSA": { "id": 19, "title": "psalms", "writer": "david", "len": 150 },
  "PRO": { "id": 20, "title": "proverbs", "writer": "solomon", "len": 31 },
  "ECC": { "id": 21, "title": "ecclesiastes", "writer": "solomon", "len": 12 },
  "SOL": { "id": 22, "title": "songofsongs", "writer": "solomon", "len": 8 },
  "ISA": { "id": 23, "title": "isaiah", "writer": "isaiah", "len": 66 },
  "JER": { "id": 24, "title": "jeremiah", "writer": "jeremiah", "len": 52 },
  "LAM": { "id": 25, "title": "lamentations", "writer": "jeremiah", "len": 5 },
  "EZE": { "id": 26, "title": "ezekiel", "writer": "ezekiel", "len": 48 },
  "DAN": { "id": 27, "title": "daniel", "writer": "daniel", "len": 12 },
  "HOS": { "id": 28, "title": "hosea", "writer": "hosea", "len": 14 },
  "JOE": { "id": 29, "title": "joel", "writer": "joel", "len": 4 },
  "AMO": { "id": 30, "title": "amos", "writer": "amos", "len": 9 },
  "OBA": { "id": 31, "title": "obadiah", "writer": "obadiah", "len": 1 },
  "JON": { "id": 32, "title": "jonah", "writer": "jonah", "len": 4 },
  "MIC": { "id": 33, "title": "micah", "writer": "micah", "len": 7 },
  "NAH": { "id": 34, "title": "nahum", "writer": "nahum", "len": 3 },
  "HAB": { "id": 35, "title": "habakkuk", "writer": "habakkuk", "len": 3 },
  "ZEP": { "id": 36, "title": "zephaniah", "writer": "zephaniah", "len": 3 },
  "HAG": { "id": 37, "title": "haggai", "writer": "haggai", "len": 2 },
  "ZEC": { "id": 38, "title": "zechariah", "writer": "zechariah", "len": 14 },
  "MAL": { "id": 39, "title": "malachi", "writer": "malachi", "len": 4 },
  "MAT": { "id": 40, "title": "matthew", "writer": "matthew", "len": 28 },
  "MAR": { "id": 41, "title": "mark", "writer": "mark", "len": 16 },
  "LUK": { "id": 42, "title": "luke", "writer": "luke", "len": 24 },
  "JOH": { "id": 43, "title": "john", "writer": "john", "len": 21 },
  "ACT": { "id": 44, "title": "acts", "writer": "luke", "len": 28 },
  "ROM": { "id": 45, "title": "romans", "writer": "paul", "len": 16 },
  "1CO": { "id": 46, "title": "corinthians1", "writer": "paul", "len": 16 },
  "2CO": { "id": 47, "title": "corinthians2", "writer": "paul", "len": 13 },
  "GAL": { "id": 48, "title": "galatians", "writer": "paul", "len": 6 },
  "EPH": { "id": 49, "title": "ephesians", "writer": "paul", "len": 6 },
  "PHI": { "id": 50, "title": "philippians", "writer": "paul", "len": 4 },
  "COL": { "id": 51, "title": "colossians", "writer": "paul", "len": 4 },
  "1TH": { "id": 52, "title": "thessalonians1", "writer": "paul", "len": 5 },
  "2TH": { "id": 53, "title": "thessalonians2", "writer": "paul", "len": 3 },
  "1TI": { "id": 54, "title": "timothy1", "writer": "paul", "len": 6 },
  "2TI": { "id": 55, "title": "timothy2", "writer": "paul", "len": 4 },
  "TIT": { "id": 56, "title": "titus", "writer": "paul", "len": 3 },
  "PHM": { "id": 57, "title": "philemon", "writer": "paul", "len": 1 },
  "HEB": { "id": 58, "title": "hebrews", "writer": "paul", "len": 13 },
  "JAM": { "id": 59, "title": "james", "writer": "james", "len": 5 },
  "1PE": { "id": 60, "title": "peter1", "writer": "peter", "len": 5 },
  "2PE": { "id": 61, "title": "peter2", "writer": "peter", "len": 3 },
  "1JO": { "id": 62, "title": "john1", "writer": "john", "len": 5 },
  "2JO": { "id": 63, "title": "john2", "writer": "john", "len": 1 },
  "3JO": { "id": 64, "title": "john3", "writer": "john", "len": 1 },
  "JUD": { "id": 65, "title": "jude", "writer": "jude", "len": 1 },
  "REV": { "id": 66, "title": "revelation", "writer": "john", "len": 22 }
};

export const books: string[] = Object.values(BookKey);

export const bookList = [
  "WholeBible",
  "OldTestament",
  "NewTestament",
  "Torah",
  "Historical",
  "Wisdom",
  "Prophetic",
  "Gospels",
  "Epistles",
  ...books,
];
