import { BookKey } from "../@types";

export const BookKeys = {
  GEN: {
    id: 1,
    title: { en: "Genesis", ar: "ٱلتَّكْوِين" },
    writer: "moses",
    len: 50,
  },
  EXO: {
    id: 2,
    title: { en: "Exodus", ar: "ٱلْخُرُوج" },
    writer: "moses",
    len: 40,
  },
  LEV: {
    id: 3,
    title: { en: "Leviticus", ar: "ٱللَّاوِيِّين" },
    writer: "moses",
    len: 27,
  },
  NUM: {
    id: 4,
    title: { en: "Numbers", ar: "ٱلْعَدَد" },
    writer: "moses",
    len: 36,
  },
  DEU: {
    id: 5,
    title: { en: "Deuteronomy", ar: "ٱلتَّثْنِيَة" },
    writer: "moses",
    len: 34,
  },
  JOS: {
    id: 6,
    title: { en: "Joshua", ar: "يَشُوع" },
    writer: "joshua",
    len: 24,
  },
  JDG: {
    id: 7,
    title: { en: "Judges", ar: "ٱلْقُضَاة" },
    writer: "samuel",
    len: 21,
  },
  RUT: {
    id: 8,
    title: { en: "Ruth", ar: "رَاعُوث" },
    writer: "samuel",
    len: 4,
  },
  "1SA": {
    id: 9,
    title: { en: "1Samuel", ar: "صَمُوئِيل ٱلْأَوَّل" },
    writer: "samuel",
    len: 31,
  },
  "2SA": {
    id: 10,
    title: { en: "2Samuel", ar: "صَمُوئِيل ٱلثَّانِي" },
    writer: "samuel",
    len: 24,
  },
  "1KI": {
    id: 11,
    title: { en: "1Kings", ar: "ٱلْمُلُوك ٱلْأَوَّل" },
    writer: "jeremiah",
    len: 22,
  },
  "2KI": {
    id: 12,
    title: { en: "2Kings", ar: "ٱلْمُلُوك ٱلثَّانِي" },
    writer: "jeremiah",
    len: 25,
  },
  "1CH": {
    id: 13,
    title: { en: "1Chronicles", ar: "أَخْبَار ٱلْأَيَّام ٱلْأَوَّل" },
    writer: "ezra",
    len: 29,
  },
  "2CH": {
    id: 14,
    title: { en: "2Chronicles", ar: "أَخْبَار ٱلْأَيَّام ٱلثَّانِي" },
    writer: "ezra",
    len: 36,
  },
  EZR: {
    id: 15,
    title: { en: "Ezra", ar: "عَزْرَا" },
    writer: "ezra",
    len: 10,
  },
  NEH: {
    id: 16,
    title: { en: "Nehemiah", ar: "نَحَمْيَا" },
    writer: "nehemiah",
    len: 13,
  },
  EST: {
    id: 17,
    title: { en: "Esther", ar: "أَسْتِير" },
    writer: "mordecai",
    len: 10,
  },
  JOB: {
    id: 18,
    title: { en: "Job", ar: "أَيُّوب" },
    writer: "moses",
    len: 42,
  },
  PSA: {
    id: 19,
    title: { en: "Psalms", ar: "ٱلْمَزَامِير" },
    writer: "david",
    len: 150,
  },
  PRO: {
    id: 20,
    title: { en: "Proverbs", ar: "ٱلْأَمْثَال" },
    writer: "solomon",
    len: 31,
  },
  ECC: {
    id: 21,
    title: { en: "Ecclesiastes", ar: "ٱلْجَامِعَة" },
    writer: "solomon",
    len: 12,
  },
  SOL: {
    id: 22,
    title: { en: "Song of Songs", ar: "نَشِيد ٱلْأَنَاشِيد" },
    writer: "solomon",
    len: 8,
  },
  ISA: {
    id: 23,
    title: { en: "Isaiah", ar: "إِشَعْيَاء" },
    writer: "isaiah",
    len: 66,
  },
  JER: {
    id: 24,
    title: { en: "Jeremiah", ar: "إِرْمِيَا" },
    writer: "jeremiah",
    len: 52,
  },
  LAM: {
    id: 25,
    title: { en: "Lamentations", ar: "مَرَاثِي إِرْمِيَا" },
    writer: "jeremiah",
    len: 5,
  },
  EZE: {
    id: 26,
    title: { en: "Ezekiel", ar: "حِزْقِيَال" },
    writer: "ezekiel",
    len: 48,
  },
  DAN: {
    id: 27,
    title: { en: "Daniel", ar: "دَانِيآل" },
    writer: "daniel",
    len: 12,
  },
  HOS: {
    id: 28,
    title: { en: "Hosea", ar: "هُوشَع" },
    writer: "hosea",
    len: 14,
  },
  JOE: { id: 29, title: { en: "Joel", ar: "يُوئِيل" }, writer: "joel", len: 3 },
  AMO: { id: 30, title: { en: "Amos", ar: "عَامُوس" }, writer: "amos", len: 9 },
  OBA: {
    id: 31,
    title: { en: "Obadiah", ar: "عُوبَدْيَا" },
    writer: "obadiah",
    len: 1,
  },
  JON: {
    id: 32,
    title: { en: "Jonah", ar: "يُونَان" },
    writer: "jonah",
    len: 4,
  },
  MIC: {
    id: 33,
    title: { en: "Micah", ar: "مِيخَا" },
    writer: "micah",
    len: 7,
  },
  NAH: {
    id: 34,
    title: { en: "Nahum", ar: "نَاحُوم" },
    writer: "nahum",
    len: 3,
  },
  HAB: {
    id: 35,
    title: { en: "Habakkuk", ar: "حَبَقُّوق" },
    writer: "habakkuk",
    len: 3,
  },
  ZEP: {
    id: 36,
    title: { en: "Zephaniah", ar: "صَفَنْيَا" },
    writer: "zephaniah",
    len: 3,
  },
  HAG: {
    id: 37,
    title: { en: "Haggai", ar: "حَجَّاي" },
    writer: "haggai",
    len: 2,
  },
  ZEC: {
    id: 38,
    title: { en: "Zechariah", ar: "زَكَرِيَّا" },
    writer: "zechariah",
    len: 14,
  },
  MAL: {
    id: 39,
    title: { en: "Malachi", ar: "مَلاَخِي" },
    writer: "malachi",
    len: 4,
  },
  MAT: {
    id: 40,
    title: { en: "Matthew", ar: "مَتَّى" },
    writer: "matthew",
    len: 28,
  },
  MAR: {
    id: 41,
    title: { en: "Mark", ar: "مَرْقُس" },
    writer: "mark",
    len: 16,
  },
  LUK: { id: 42, title: { en: "Luke", ar: "لُوقَا" }, writer: "luke", len: 24 },
  JOH: {
    id: 43,
    title: { en: "John", ar: "يُوحَنَّا" },
    writer: "john",
    len: 21,
  },
  ACT: {
    id: 44,
    title: { en: "Acts", ar: "أَعْمَال ٱلرُّسُل" },
    writer: "luke",
    len: 28,
  },
  ROM: {
    id: 45,
    title: { en: "Romans", ar: "رُومِيَة" },
    writer: "paul",
    len: 16,
  },
  "1CO": {
    id: 46,
    title: { en: "1Corinthians", ar: "كُورِنْثُوس ٱلْأُولَى" },
    writer: "paul",
    len: 16,
  },
  "2CO": {
    id: 47,
    title: { en: "2Corinthians", ar: "كُورِنْثُوس ٱلثَّانِيَة" },
    writer: "paul",
    len: 13,
  },
  GAL: {
    id: 48,
    title: { en: "Galatians", ar: "غَلاَطِيَّة" },
    writer: "paul",
    len: 6,
  },
  EPH: {
    id: 49,
    title: { en: "Ephesians", ar: "أَفَسُس" },
    writer: "paul",
    len: 6,
  },
  PHI: {
    id: 50,
    title: { en: "Philippians", ar: "فِيلِبِّي" },
    writer: "paul",
    len: 4,
  },
  COL: {
    id: 51,
    title: { en: "Colossians", ar: "كُولُوسِّي" },
    writer: "paul",
    len: 4,
  },
  "1TH": {
    id: 52,
    title: { en: "1Thessalonians", ar: "تَسَالُونِيكِي ٱلْأُولَى" },
    writer: "paul",
    len: 5,
  },
  "2TH": {
    id: 53,
    title: { en: "2Thessalonians", ar: "تَسَالُونِيكِي ٱلثَّانِيَة" },
    writer: "paul",
    len: 3,
  },
  "1TI": {
    id: 54,
    title: { en: "1Timothy", ar: "تِيمُوثَاوُس ٱلْأُولَى" },
    writer: "paul",
    len: 6,
  },
  "2TI": {
    id: 55,
    title: { en: "2Timothy", ar: "تِيمُوثَاوُس ٱلثَّانِيَة" },
    writer: "paul",
    len: 4,
  },
  TIT: { id: 56, title: { en: "Titus", ar: "تِيطُس" }, writer: "paul", len: 3 },
  PHM: {
    id: 57,
    title: { en: "Philemon", ar: "فِيلِيمُون" },
    writer: "paul",
    len: 1,
  },
  HEB: {
    id: 58,
    title: { en: "Hebrews", ar: "ٱلْعِبْرَانِيِّين" },
    writer: "paul",
    len: 13,
  },
  JAM: {
    id: 59,
    title: { en: "James", ar: "يَعْقُوب" },
    writer: "james",
    len: 5,
  },
  "1PE": {
    id: 60,
    title: { en: "1Peter", ar: "بُطْرُس ٱلْأُولَى" },
    writer: "peter",
    len: 5,
  },
  "2PE": {
    id: 61,
    title: { en: "2Peter", ar: "بُطْرُس ٱلثَّانِيَة" },
    writer: "peter",
    len: 3,
  },
  "1JO": {
    id: 62,
    title: { en: "1John", ar: "يُوحَنَّا ٱلْأُولَى" },
    writer: "john",
    len: 5,
  },
  "2JO": {
    id: 63,
    title: { en: "2John", ar: "يُوحَنَّا ٱلثَّانِيَة" },
    writer: "john",
    len: 1,
  },
  "3JO": {
    id: 64,
    title: { en: "3John", ar: "يُوحَنَّا ٱلثَّالِثَة" },
    writer: "john",
    len: 1,
  },
  JUD: {
    id: 65,
    title: { en: "Jude", ar: "يَهُوذَا" },
    writer: "jude",
    len: 1,
  },
  REV: {
    id: 66,
    title: { en: "Revelation", ar: "ٱلرُّؤْيَا" },
    writer: "john",
    len: 22,
  },
};

export const books: string[] = Object.values(BookKey);

export const bookList = [
  "WholeBible",
  "OldTestament",
  "NewTestament",
  "Torah",
  "Historical",
  "Wisdom",
  "Prophetic",
  "Gospels",
  "Epistles",
  ...books,
];
