export const ERROR_KEYS = {
  UNKNOWN_ERROR: "unknownError",
  EMAIL_NOT_FOUND: "emailNotFound",
  USER_NOT_FOUND: "userNotFound",
  PROFILE_NOT_FOUND: "profileNotFound",
  USER_NOT_CREATED: "userNotCreated",
  LOGIN_FAILED: "loginFailed",
  LOGOUT_FAILED: "logoutFailed",
  ACCOUNT_LOCKED: "accountLocked",
  USER_DUPLICATION: "userDuplication",
  PASSWORD_INVALID: "passwordInvalid",
  PASSWORD_MISMATCH: "passwordMismatch",
  PASSWORD_TOO_SHORT: "passwordTooShort",
  INVALID_OR_EXPIRED_TOKEN: "invalidOrExpiredToken",
  SESSION_EXPIRED: "sessionExpired",
  SESSION_NOT_EXIST: "sessionNotExist",
  UNAUTHORIZED_ACCESS: "unauthorizedAccess",
  FAILED_TO_FETCH: "failedToFetch",
  FAILED_TO_CHANGE_LANGUAGE: "failedToChangeLanguage",
  HIGHLIGHT_VERSE: "highlightVerse",
  HIGHLIGHT_SINGLE_VERSE_ONLY: "highlightSingleVerseOnly",
  NO_OLD_PASSWORD_FOUND: "noOldPasswordFound",
  BOOKMARK_NOT_FOUND: "bookmarkNotFound",
  BOOKMARK_EXCEED_LIMIT: "bookmarkExceedLimit",
  VERSE_GROUP_FAVORITED :"verseGroupFavorited",
  VERSE_GROUP_FEATURED: "verseGroupFeatured",
} as const;
