### Get all books
GET http://localhost:5000/api/books

### Get verses of one chapter
GET http://localhost:5000/api/verses/GEN/1/en

### Find a verse contains search keywords
# TO DO
POST http://localhost:5000/api/verses/query
Content-Type: application/json

{
  "query": "Lord Israel",
  "selectedBooks": ["GEN", "EXO"]
}