POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
  "email": "emadunan@gmail.com",
  "password": "emadunan",
  "provider": "local",
  "providerId": "emadunan",
  "displayName": "Emad Younan",
  "isActive": true
}

###

POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "emadunan@gmail.com",
  "password": "emadunan"
}

###

DELETE http://localhost:5000/users/7b54832c-e75a-48bf-ad56-c632a29a690c HTTP/1.1

###

GET http://localhost:5000/users HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWR1bmFuQGdtYWlsLmNvbSIsInN1YiI6ImI1NjNjMDA1LTc3YzQtNDUwOS1hNmE5LWUxYzkzNTM4MDMxMiIsImlhdCI6MTczOTMwNzg5OSwiZXhwIjoxNzM5MzExNDk5fQ.2QrqIs6yU6WEbIJ6P5P82CcGPa8coj644UqgwlevTkA