### Test app controller root
GET http://localhost:5000


### Register new user
POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
  "email": "emadunan@gmail.com",
  "password": "emadunan",
  "provider": "facebook",
  "providerId": "emadunan",
  "displayName": "Emad Younan",
  "isActive": true
}

### Login
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "emadunan@gmail.com",
  "password": "emadunan"
}

### Delete user
DELETE http://localhost:5000/users/c423e3ae-eb95-410b-80b0-0f04e2e726b4 HTTP/1.1

### Get app users -- protected resource
GET http://localhost:5000/users HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWR1bmFuQGdtYWlsLmNvbSIsInN1YiI6IjYzMWJkMmJlLTIxYWEtNDhjNS04NWM3LTY1ZmZkMDU3YTU4NyIsImlhdCI6MTczOTUyOTIxNCwiZXhwIjoxNzM5NTMyODE0fQ.7Y5VO135vn2eJhqlW9dw1LikXUOQfaLtolxM0DUKInQ