export enum AuditingAction {
  CREATE_PROFILE = 'CREATE_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  DELETE_PROFILE = 'DELETE_USER',
  RESET_PASSWORD = 'RESET_PASSWORD',
  SEARCH_BIBLE = 'SEARCH_BIBLE',
  OPEN_CHAPTER = 'OPEN_CHAPTER',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
}
