export enum Permission {
  LOGIN_ADMINSITE = "login_adminsite",
  READ_DASHBOARD = "read_dashboard",
  READ_MEMBERS = "read_members",
  WRITE_MEMBERS = "write_members",
  READ_AUDITING = "read_auditing",
  MANAGE_VERSE_GROUPS = "manage_verse_groups",
  MANAGE_FEATURED = "manage_featured",
  WRITE_BLOG = "write_blog",
  CREATE_GLOSSARY_TERM = "create_glossary_term",
  UPDATE_GLOSSARY_TERM = "update_glossary_term",
  APPROVE_GLOSSARY_TERM = "approve_glossary_term",
  CREATE_LIBRARY_BOOK = "create_library_book",
  UPDATE_LIBRARY_BOOK = "update_library_book",
  DELETE_LIBRARY_BOOK = "delete_librart_book",
  APPROVE_LIBRARY_BOOK = "approve_library_book",
}
