### Get all books
GET http://localhost:5000/books

### Get verses of one chapter
GET http://localhost:5000/verses/01_GEN/1/en

### Find a verse contains search keywords
# TO DO
POST http://localhost:5000/verses/query
Content-Type: application/json

{
  "query": "الرب",
  "selectedBooks": ["01_GEN", "02_EXO"]
}