### Login
POST http://localhost:5000/api/auth/local HTTP/1.1
Content-Type: application/json

{
  "email": "emadunan@gmail.com",
  "password": "emadunan"
}

### Refresh token
POST http://localhost:5000/api/auth/refresh

### Get me
GET http://localhost:5000/api/auth/me

### Get protected resource
GET http://localhost:5000/api/users