name: Deploy to Production Environment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: SSH into Server and Deploy
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "
          cd /home/${{ vars.SERVER_USER }}/projects/amen24prod &&
          git pull origin deploy &&
          cd ./_scripts && ./deployToProd.sh"
