name: Deploy to Test Environment

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
  
      - name: SSH into Server
        run: ssh -i private_key -o StrictHostKeyChecking=no emad@164.92.231.145 "cd /home/emad/projects/amen24/ && git pull origin test && cd ./_scripts && ./deployToTest.sh"
